//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessangerServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public string Message1 { get; set; }
        public int IDUserGet { get; set; }
        public int IDUserSent { get; set; }
        public System.DateTime TimeSent { get; set; }
        public byte[] Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
